spring:
  application:
    name: Swag
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    default-property-inclusion: non_null
  mail:
    host: localhost
    port: 12345
  messages:
    basename: i18n/messages
  data:
    mongodb:
      auto-index-creation: false

application:
  project:
    contact: "contact@swag.com"
  libraries:
    errors:
      enabled: true
    security:
      enabled: true
      jwt:
        enabled: true
        secretKey: change-me-i-must-be-super-long-change-me-i-must-be-super-long-change-me-i-must-be-super-long
      cors:
        allowed-origins:
          - "*"
        allowed-methods:
          - "GET"
          - "PUT"
          - "POST"
          - "DELETE"
          - "OPTIONS"
        allowed-headers: "*"
        exposed-headers:
          - "Content-Type"
          - "Content-Language"
          - "Expires"
          - "Cache-Control"
          - "Last-Modified"
        allow-credentials: true
        max-age: 1800
    mongodb:
      migrations:
        enabled: true
        migration-package: com.vguivarc.musicme.backend.config.migrations

management:
  endpoints:
    web:
      exposure:
        include: "health"
  health:
    defaults:
      enabled: false
    mongo:
      enabled: true
    mail:
      enabled: false
  endpoint:
    health:
      enabled: true
      show-details: always

server:
  port: ${PORT:8080}
