spring:
  data:
    mongodb:
      uri: set-me-in-env-vars
      database: mongodb-musicme
  mail:
    host: smtp.eu.mailgun.org
    port: 587
    username: you-can-set-me-here
    password: set-me-in-env-vars

cors:
  configurations:
    - path: "/**"
      configuration:
        allowed-origins:
          - "*"
        allowed-methods:
          - "*"
        allowed-headers:
          - "*"

application:
  project:
    administration-url: "http://admin.musicme.swag.com"
  libraries:
    security:
      jwt:
        secretKey: set-me-in-env-vars
